import 'dart:math';

var v_p = [
  "Your positivity brightens the world around you.",
  "Your optimism is contagious and inspiring.",
  "Your positivity knows no bounds.",
  "Your radiant positivity uplifts everyone you encounter.",
  "Your positive energy is boundless and infectious.",
  "Your outlook on life is overwhelmingly positive.",
  "Your positive attitude is a beacon of light in any situation.",
  "Your unwavering positivity is truly remarkable.",
  "Your positivity is a powerful force for good in the world.",
  "Your overwhelming positivity is a gift to those around you.",
  "Your positive mindset is a driving force for success.",
  "Your positivity is like a ray of sunshine on a cloudy day.",
  "Your optimism knows no limits.",
  "Your positivity illuminates even the darkest of times.",
  "Your positivity is a source of strength and resilience.",
  "Your positive spirit lifts the spirits of others.",
  "Your unwavering positivity is truly inspiring.",
  "Your positivity changes things.",
  "Your positive outlook on life is truly admirable.",
  "Your overwhelming positivity is a testament to your strength.",
];
var pos  =[
  "You are quite positive!",
  "You're radiating positivity recently!",
  "Spread your enthusiasm",
  "Your positivity is lighting up the room!",
  "You're beaming with positivity!",
  "Your positivity is truly inspiring!",
  "You're a ray of sunshine!",
  "Your positive attitude is uplifting!",
  "Your optimism is refreshing!",
  "Your positivity makes a difference!",
  "You're a beacon of positivity!",
  "You're overflowing with positivity!",
  "You're exuding positivity!",
  "Your positivity is illuminating!",
  "Your positive energy is palpable!",
];
var s_p = [
  "It seems like your enthusiasm could use a boost. Is there anything on your mind?",
  "You seem a bit less enthusiastic than usual. Is there something bothering you?",
  "I sense a hint of subdued enthusiasm. Is everything okay?",
  "Your enthusiasm seems a bit subdued today. Is there anything I can do to help?",
  "Your energy seems a bit muted. Is there something you'd like to talk about?",
  "I notice a subtle lack of enthusiasm. Is there anything you'd like to share?",
  "Your excitement seems a bit toned down. Is there something weighing on you?",
  "I'm picking up on a slight decrease in your usual enthusiasm. Is everything alright?",
  "Your enthusiasm level seems a bit lower than usual. Would you like to talk about it?",
  "It seems like your enthusiasm is a bit subdued. How can I support you?",
  "Your usual enthusiasm feels a bit muted today. Is there anything on your mind?",
  "I sense a slight decrease in your enthusiasm. Is there something you need?",
  "Your excitement seems to be dialed down. Is there something bothering you?",
  "It appears that your enthusiasm has waned a bit. Is there anything I can do to help?",
  "I notice a slight lack of enthusiasm. Is there anything you'd like to discuss?",
  "Your enthusiasm seems a bit muted today. Would you like to talk about it?",
  "Your usual enthusiasm appears to be subdued. Is there something you're feeling?",
  "I'm sensing a decrease in your usual enthusiasm. Is there anything you'd like to share?",
  "Your energy feels a bit muted. Is there something you'd like to address?",
  "It seems like your enthusiasm is not as vibrant as usual. Is everything okay?",
];
var b = [
  "I sense a neutral emotional state. How are you feeling today?",
  "You seem to be in a neutral emotional state. Is there anything on your mind?",
  "Your emotions appear to be neutral. Is there something you'd like to talk about?",
  "It seems like you're feeling neutral. Is there anything I can assist you with?",
  "Your emotional state seems balanced and neutral. Is everything okay?",
  "You appear to be experiencing neutrality in your emotions. How can I support you?",
  "I'm detecting a neutral emotional vibe from you. Is there something you need?",
  "Your emotions seem neutral today. Would you like to share what's on your mind?",
  "You're projecting a neutral emotional aura. Is there anything you'd like to discuss?",
  "Your emotional state seems to be neutral. Is there something you're pondering?",
  "I'm sensing neutrality in your emotions. Is there anything you're feeling uncertain about?",
  "It appears that you're in a state of emotional neutrality. How can I assist you?",
  "Your emotional state seems neutral. Is there something you'd like to address?",
  "You're exhibiting a neutral emotional demeanor. Is there anything you'd like to share?",
  "I sense neutrality in your emotions. Is there something you'd like to explore?",
  "Your emotions seem to be in a neutral zone. Is there anything you'd like to talk about?",
  "You're emanating a sense of emotional neutrality. Is there anything you're considering?",
  "Your emotional state appears to be neutral. Is there something you're processing?",
  "I'm picking up on a neutral emotional vibe. Is there anything you'd like to discuss?",
  "You seem to be in a state of emotional neutrality. Is everything alright?",
];
var s_n = [
  "I'm sensing a hint of negativity. Is there something on your mind?",
  "Your tone seems slightly negative. Is there anything bothering you?",
  "I sense a subtle note of negativity. Is there something you'd like to talk about?",
  "Your energy feels a bit low. Is there something bringing you down?",
  "I'm picking up on a slight negativity in your demeanor. Would you like to share?",
  "Your mood seems slightly negative today. Is there anything I can do to help?",
  "You seem to be experiencing a touch of negativity. Is everything okay?",
  "I'm detecting a hint of negativity in your voice. Is there something troubling you?",
  "Your words have a tinge of negativity. Is there something you need to get off your chest?",
  "I sense a subtle negativity in your emotions. Is there anything you'd like to discuss?",
  "Your attitude seems slightly negative. Is there something you're unhappy about?",
  "Your vibe feels a bit negative. Is there anything I can do to support you?",
  "I'm noticing a slight negativity in your demeanor. Is there something bothering you?",
  "Your outlook appears to be slightly negative. Is there something weighing on your mind?",
  "I'm sensing a touch of negativity in your mood. Is there anything you'd like to talk through?",
  "Your energy feels a bit down. Is there something that's been bothering you lately?",
  "Your demeanor seems slightly negative today. Is there anything you'd like to share?",
  "I sense a slight undercurrent of negativity. Is there something troubling you?",
  "Your mood seems a bit off. Is there anything you'd like to address?",
  "I'm picking up on a subtle negativity. Is there something you need help with?",
];
var neg = [
  "Feeling down?",
  "You seem off.",
  "Rough day?",
  "Everything okay?",
  "Something bothering you?",
  "Need to talk?",
  "Feeling negative?",
  "Anything on your mind?",
  "You seem upset.",
  "Having a tough time?",
  "Feeling low?",
  "Need a pick-me-up?",
  "Struggling?",
  "Need support?",
  "Feeling downbeat?",
  "You seem down.",
  "Need to vent?",
  "Feeling negative vibes?",
  "Need a listening ear?",
  "Feeling pessimistic?",
];

var help = [
  "It's okay to ask for help when you need it.",
  "You don't have to go through this alone. Reach out for support.",
  "Seeking help is a sign of strength, not weakness.",
  "You deserve to receive the support you need.",
  "Don't hesitate to reach out to someone you trust.",
  "There are people who care about you and want to help.",
  "You're not alone in this. Many are willing to support you.",
  "Talking to someone can make a world of difference.",
  "You have the right to prioritize your mental health.",
  "There are professionals trained to help you navigate through tough times.",
  "You deserve to feel better, and seeking help is the first step.",
  "You deserve support and understanding.",
  "There is no shame in seeking help to improve your well-being.",
  "Taking care of yourself includes seeking help when necessary.",
  "You are not weak for reaching out; you are brave.",
  "There are resources available to assist you on your journey.",
  "You have the power to make positive changes in your life with support.",
  "Reaching out for help is a positive step towards healing.",
  "You deserve to live a fulfilling life, and seeking help can guide you there.",
  "You are worthy of receiving help and support.",
];
String str_senti(var arr)=> arr[Random().nextInt(arr.length)];
// Makes message based on sentiment value
// param Senti: calculated sentiment
// Returns: String, the response
String msg(var senti)=>
    switch(senti) {
      >=5 => str_senti(v_p),
      <=4 && >2 => str_senti(pos),
      <=2 && >0 => str_senti(s_p),
      0 => str_senti(b),
      <=-1 && >-4 => str_senti(s_n),
      <=-1 && >-5 => str_senti(neg),
      <= -5 => str_senti(help),
      _ => 'No journal entries today! Any thoughts today?'
};